/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import modelo.PokemonVO;
import servicos.PokemonServicos;
import servicos.ServicosFactory;

/**
 *
 * @author Marlon Martins   
 * @since 06/05/2018 - 05:47
 * @version 1.0 red
 */
public class GUICadPokemon extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUICadPokemon
     */
    public GUICadPokemon() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlpDados = new javax.swing.JLayeredPane();
        jlNome = new javax.swing.JLabel();
        jlTipo = new javax.swing.JLabel();
        jlCategoria = new javax.swing.JLabel();
        jlPeso = new javax.swing.JLabel();
        jlAltura = new javax.swing.JLabel();
        jlHabilidade = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jtTipo = new javax.swing.JTextField();
        jtCategoria = new javax.swing.JTextField();
        jtPeso = new javax.swing.JTextField();
        jtAltura = new javax.swing.JTextField();
        jtHabilidade = new javax.swing.JTextField();
        jlpAcoes = new javax.swing.JLayeredPane();
        jbCadastro = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Pokemon");

        jlpDados.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlNome.setText("Nome");

        jlTipo.setText("Tipo");

        jlCategoria.setText("Categoria");

        jlPeso.setText("Peso");

        jlAltura.setText("Altura");

        jlHabilidade.setText("Habilidade");

        jtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtNomeKeyPressed(evt);
            }
        });

        jtTipo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtTipoKeyPressed(evt);
            }
        });

        jtCategoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtCategoriaKeyPressed(evt);
            }
        });

        jtPeso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtPesoKeyPressed(evt);
            }
        });

        jtAltura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtAlturaKeyPressed(evt);
            }
        });

        jtHabilidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtHabilidadeKeyPressed(evt);
            }
        });

        jlpDados.setLayer(jlNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlTipo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlCategoria, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlPeso, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlAltura, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlHabilidade, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtTipo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtCategoria, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtPeso, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtAltura, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtHabilidade, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpDadosLayout = new javax.swing.GroupLayout(jlpDados);
        jlpDados.setLayout(jlpDadosLayout);
        jlpDadosLayout.setHorizontalGroup(
            jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jlpDadosLayout.createSequentialGroup()
                        .addComponent(jlNome)
                        .addGap(18, 18, 18)
                        .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jlpDadosLayout.createSequentialGroup()
                        .addComponent(jlTipo)
                        .addGap(18, 18, 18)
                        .addComponent(jtTipo))
                    .addGroup(jlpDadosLayout.createSequentialGroup()
                        .addComponent(jlCategoria)
                        .addGap(18, 18, 18)
                        .addComponent(jtCategoria))
                    .addGroup(jlpDadosLayout.createSequentialGroup()
                        .addComponent(jlPeso)
                        .addGap(18, 18, 18)
                        .addComponent(jtPeso))
                    .addGroup(jlpDadosLayout.createSequentialGroup()
                        .addComponent(jlAltura)
                        .addGap(18, 18, 18)
                        .addComponent(jtAltura))
                    .addGroup(jlpDadosLayout.createSequentialGroup()
                        .addComponent(jlHabilidade)
                        .addGap(18, 18, 18)
                        .addComponent(jtHabilidade)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jlpDadosLayout.setVerticalGroup(
            jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNome)
                    .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTipo)
                    .addComponent(jtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCategoria)
                    .addComponent(jtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPeso)
                    .addComponent(jtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlAltura)
                    .addComponent(jtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlHabilidade)
                    .addComponent(jtHabilidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jlpAcoes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbCadastro.setText("Cadastro");
        jbCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastroActionPerformed(evt);
            }
        });
        jbCadastro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbCadastroKeyPressed(evt);
            }
        });

        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });
        jbLimpar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbLimparKeyPressed(evt);
            }
        });

        jlpAcoes.setLayer(jbCadastro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAcoes.setLayer(jbLimpar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpAcoesLayout = new javax.swing.GroupLayout(jlpAcoes);
        jlpAcoes.setLayout(jlpAcoesLayout);
        jlpAcoesLayout.setHorizontalGroup(
            jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpAcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jlpAcoesLayout.setVerticalGroup(
            jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpAcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(jbLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlpDados)
                    .addComponent(jlpAcoes))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlpDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlpAcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastroActionPerformed
        cadastrar();
        limpar();
    }//GEN-LAST:event_jbCadastroActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        limpar();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNomeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtTipo.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jtNomeKeyPressed

    private void jtTipoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtTipoKeyPressed
       if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtCategoria.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jtTipoKeyPressed

    private void jtCategoriaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtCategoriaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtPeso.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jtCategoriaKeyPressed

    private void jtPesoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPesoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtAltura.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jtPesoKeyPressed

    private void jtAlturaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtAlturaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtHabilidade.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jtAlturaKeyPressed

    private void jtHabilidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtHabilidadeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jbCadastro.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jtHabilidadeKeyPressed

    private void jbCadastroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbCadastroKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cadastrar();
            limpar();
        }//fecha if
    }//GEN-LAST:event_jbCadastroKeyPressed

    private void jbLimparKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbLimparKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            limpar();
        }//fecha if
    }//GEN-LAST:event_jbLimparKeyPressed

    private void cadastrar(){
        try {
            PokemonVO pVO = new PokemonVO();
            String nome=jtNome.getText();
            if(nome.isEmpty()){
                throw new NumberFormatException("Preencha o nome!");
            }
            pVO.setNome(jtNome.getText());
            
            String tipo=jtTipo.getText();
            if(tipo.isEmpty()){
                throw new NumberFormatException("Preencha o tipo!");
            }
            pVO.setTipo(jtTipo.getText());
            
            String categoria=jtCategoria.getText();
            if(categoria.isEmpty()){
                throw new NumberFormatException("Preencha a categoria!");
            }
            pVO.setCategoria(jtCategoria.getText());
            
            String peso=jtPeso.getText();
            if(peso.isEmpty()){
                throw new NumberFormatException("Preencha o peso!");
            }
            pVO.setPeso(Float.parseFloat(jtPeso.getText()));
            
            String altura=jtAltura.getText();
            if(altura.isEmpty()){
                throw new NumberFormatException("Preencha a altura!");
            }
            pVO.setAltura(Float.parseFloat(jtAltura.getText()));
            
            String habilidade=jtHabilidade.getText();
            if(habilidade.isEmpty()){
                throw new NumberFormatException("Preencha a habilidade!");
            }
            pVO.setHabilidade(jtHabilidade.getText());
            
            PokemonServicos ps = ServicosFactory.getPokemonServicos();
            ps.cadastrarPokemon(pVO);
            
            JOptionPane.showMessageDialog(
                    this, 
                    "Pokemon Registrado com sucesso!");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this, 
                    "Erro! "+e.getMessage());
        } 
    }//fecha cadastrar
    
    private void limpar(){
        jtNome.setText(null);
        jtTipo.setText(null);
        jtCategoria.setText(null);
        jtPeso.setText(null);
        jtAltura.setText(null);
        jtHabilidade.setText(null);
        jtNome.grabFocus();
    }//fecha limpar

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbCadastro;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JLabel jlAltura;
    private javax.swing.JLabel jlCategoria;
    private javax.swing.JLabel jlHabilidade;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlPeso;
    private javax.swing.JLabel jlTipo;
    private javax.swing.JLayeredPane jlpAcoes;
    private javax.swing.JLayeredPane jlpDados;
    private javax.swing.JTextField jtAltura;
    private javax.swing.JTextField jtCategoria;
    private javax.swing.JTextField jtHabilidade;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtPeso;
    private javax.swing.JTextField jtTipo;
    // End of variables declaration//GEN-END:variables
}
